name: Selecciona el tipo de issue
description: Elige el tipo de contribuci贸n que deseas hacer
blank_issues_enabled: false
contact_links:
  - name:  Documentaci贸n del Proyecto
    url: https://github.com/ernestobarrera/filters/wiki
    about: Consulta nuestra documentaci贸n antes de crear una issue

# Configuraci贸n de las plantillas
templates:
  - name:  Nuevo Filtro
    about: Proponer un nuevo filtro de b煤squeda
    filename: nuevo_filtro.md
  - name:  Modificar Filtro Existente
    about: Proponer cambios a un filtro existente
    filename: modificar_filtro.md
